to_do_list = list((1, 2, 3, 4, 5))
print(to_do_list)
the_first_list = ["eat", "sleep", "sleep", "sleep", "sleep", "code", "repeat", "repeat", "repeat", "repeat", "repeat", "code", "code", "code", "code", "code", "code"]
print(f"i will do the first thing: {the_first_list[0]}")
a = to_do_list.index(3)
print(a)
b = the_first_list.index("eat")
print(b)
c = the_first_list.count("code")
print(c)
print(len(the_first_list))
the_first_list.insert(12,"dumping")
the_first_list.append("studying")
the_first_list.extend(["running","walking","jumping"])
print(the_first_list)
the_first_list.remove("sleep")
print(the_first_list)
the_first_list.pop(15)
del the_first_list[0]
print(the_first_list)
the_first_list.clear()
print(the_first_list)
the_tuple = (1, 2, 3, 4, 5)